# docker-compose.yml
version: '3'
services:
  cronapi:
    build:
      context: .
      dockerfile: dockerfile
    image: schirrock/cronapi:0.0.1
    ports:
      - "49501:8000"
    container_name: cronapi
    networks:
      - cloudflare

networks:
  cloudflare:
    external: true
