# docker-compose.yml
version: '3'
services:
  cronapi:
    build:
      context: .
      dockerfile: dockerfile
    image: schirrock/cronapi:0.0.1
    ports:
      - "49501:8000"
    container_name: cronapi
    networks:
      - cloudflare
    environment:
      - MONGO_URI=mongodb://root:ea02910866ed4c0f9a982a489f606b76@mongo_db:27017/cronapi?authSource=admin
      - SECRET_KEY=idontgiveashit

networks:
  cloudflare:
    external: true
